#! python3

import bs4, requests, webbrowser

url = "https://www.poesiasonline.com"

print("Insira um tema de procura!")
inp=input()
#print(url+inp)
link = url + "/" +inp
res=requests.get(url)
res.raise_for_status()
file = open("poesiasonline.html", "wb")

for chunk in res.iter_content(10000000):
    file.write(chunk)
file.close()
