#! python3

import bs4, requests, webbrowser

url = "https://www.poesiasonline.com"

print("Insira um tema de procura!")
inp=input()
#print(url+inp)
for i in range(1,5):
    print("a ir á pagina",i)
    link = url + "/"+inp+ "/page/"+ str(i)
    res=requests.get(link)
    try:
        res.raise_for_status()
    except Exception as e:
        print(e)
        continue
    nome=inp+str(i)+".html"
    file = open(nome, "wb")

    for chunk in res.iter_content(10000000):
        file.write(chunk)
    file.close()
